services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - tmplt-nw
  api: &api
    build:
      context: .
      dockerfile: docker/local/django/Dockerfile
    container_name: api
    command: /start
    volumes:
      - .:/app:z
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - redis
      - mailpit
      - postgres
    networks:
      - tmplt-nw
  mailpit:
    image: docker.io/axllent/mailpit:v1.20.3
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - tmplt-nw
  celery_worker:
    <<: *api
    command: /start-celeryworker
    container_name: celery_worker
  flower:
    <<: *api
    command: /start-flower
    ports:
      - "5557:5555"
    container_name: flower
  postgres:
    image: postgres:17-bullseye
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - tmplt-nw
  nginx:
    restart: always
    depends_on:
      - api
    volumes:
      - static_volume:/app/staticfiles
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - tmplt-nw
networks:
  tmplt-nw:
    driver: bridge
volumes:
  static_volume:
  mailpit_data:
  postgres_data:
