services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - tmplt-nw
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: api
    command: /start
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - tmplt-nw
networks:
  tmplt-nw:
    driver: bridge
volumes:
  static_volume:
