# Generated by Django 4.2.17 on 2025-01-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TgAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temporary_token",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "temporary_token_expiration",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tg",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Account",
                "verbose_name_plural": "Telegram Accounts",
            },
        ),
    ]
